// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1) {
  return window['go']['main']['App']['AIChat'](arg1);
}

export function AIToolExecute(arg1) {
  return window['go']['main']['App']['AIToolExecute'](arg1);
}

export function CrackShadowHash(arg1) {
  return window['go']['main']['App']['CrackShadowHash'](arg1);
}

export function CrackShadowPickWordlist() {
  return window['go']['main']['App']['CrackShadowPickWordlist']();
}

export function GetPlaybookCatalog() {
  return window['go']['main']['App']['GetPlaybookCatalog']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListOllamaModels(arg1) {
  return window['go']['main']['App']['ListOllamaModels'](arg1);
}

export function LocalListDir(arg1) {
  return window['go']['main']['App']['LocalListDir'](arg1);
}

export function LocalReadText(arg1, arg2) {
  return window['go']['main']['App']['LocalReadText'](arg1, arg2);
}

export function LocalWriteText(arg1, arg2) {
  return window['go']['main']['App']['LocalWriteText'](arg1, arg2);
}

export function MySQLConnect(arg1) {
  return window['go']['main']['App']['MySQLConnect'](arg1);
}

export function MySQLDisconnect() {
  return window['go']['main']['App']['MySQLDisconnect']();
}

export function MySQLIsConnected() {
  return window['go']['main']['App']['MySQLIsConnected']();
}

export function MySQLListDatabases() {
  return window['go']['main']['App']['MySQLListDatabases']();
}

export function MySQLListTables(arg1) {
  return window['go']['main']['App']['MySQLListTables'](arg1);
}

export function MySQLRunSQL(arg1) {
  return window['go']['main']['App']['MySQLRunSQL'](arg1);
}

export function MySQLSearchKeyword(arg1) {
  return window['go']['main']['App']['MySQLSearchKeyword'](arg1);
}

export function RunPlaybookItem(arg1) {
  return window['go']['main']['App']['RunPlaybookItem'](arg1);
}

export function SFTPDownloadDialog(arg1) {
  return window['go']['main']['App']['SFTPDownloadDialog'](arg1);
}

export function SFTPListDir(arg1) {
  return window['go']['main']['App']['SFTPListDir'](arg1);
}

export function SFTPReadText(arg1, arg2) {
  return window['go']['main']['App']['SFTPReadText'](arg1, arg2);
}

export function SFTPUploadDialog(arg1) {
  return window['go']['main']['App']['SFTPUploadDialog'](arg1);
}

export function SFTPWriteText(arg1, arg2) {
  return window['go']['main']['App']['SFTPWriteText'](arg1, arg2);
}

export function SSHConnect(arg1) {
  return window['go']['main']['App']['SSHConnect'](arg1);
}

export function SSHDisconnect() {
  return window['go']['main']['App']['SSHDisconnect']();
}

export function SSHExec(arg1) {
  return window['go']['main']['App']['SSHExec'](arg1);
}

export function SSHGrepRecursive(arg1) {
  return window['go']['main']['App']['SSHGrepRecursive'](arg1);
}

export function SSHGuardAnalysis(arg1) {
  return window['go']['main']['App']['SSHGuardAnalysis'](arg1);
}

export function SSHIsConnected() {
  return window['go']['main']['App']['SSHIsConnected']();
}

export function SSHSearchFlags(arg1) {
  return window['go']['main']['App']['SSHSearchFlags'](arg1);
}

export function SSHShellResize(arg1, arg2) {
  return window['go']['main']['App']['SSHShellResize'](arg1, arg2);
}

export function SSHShellWrite(arg1) {
  return window['go']['main']['App']['SSHShellWrite'](arg1);
}

export function SSHSignalPids(arg1) {
  return window['go']['main']['App']['SSHSignalPids'](arg1);
}

export function SSHStartShell(arg1) {
  return window['go']['main']['App']['SSHStartShell'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartLocalForward(arg1) {
  return window['go']['main']['App']['StartLocalForward'](arg1);
}

export function StopLocalForward(arg1) {
  return window['go']['main']['App']['StopLocalForward'](arg1);
}
