// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {playbook} from '../models';
import {config} from '../models';
import {mysqlmgr} from '../models';
import {sshx} from '../models';

export function AIChat(arg1:main.ChatRequest):Promise<main.ChatResponse>;

export function AIToolExecute(arg1:main.ToolExecuteRequest):Promise<main.ToolExecuteResponse>;

export function CrackShadowHash(arg1:main.CrackShadowRequest):Promise<main.CrackShadowResponse>;

export function CrackShadowPickWordlist():Promise<string>;

export function GetPlaybookCatalog():Promise<playbook.Catalog>;

export function GetSettings():Promise<config.Settings>;

export function ListOllamaModels(arg1:string):Promise<Array<string>>;

export function LocalListDir(arg1:string):Promise<Array<main.LocalEntry>>;

export function LocalReadText(arg1:string,arg2:number):Promise<string>;

export function LocalWriteText(arg1:string,arg2:string):Promise<void>;

export function MySQLConnect(arg1:main.MySQLConnectRequest):Promise<void>;

export function MySQLDisconnect():Promise<void>;

export function MySQLIsConnected():Promise<boolean>;

export function MySQLListDatabases():Promise<Array<string>>;

export function MySQLListTables(arg1:string):Promise<Array<string>>;

export function MySQLRunSQL(arg1:main.MySQLRunRequest):Promise<mysqlmgr.Result>;

export function MySQLSearchKeyword(arg1:main.MySQLKeywordSearchRequest):Promise<mysqlmgr.KeywordSearchResponse>;

export function RunPlaybookItem(arg1:main.RunItemRequest):Promise<sshx.ExecResult>;

export function SFTPDownloadDialog(arg1:string):Promise<void>;

export function SFTPListDir(arg1:string):Promise<Array<sshx.SFTPEntry>>;

export function SFTPReadText(arg1:string,arg2:number):Promise<string>;

export function SFTPUploadDialog(arg1:string):Promise<void>;

export function SFTPWriteText(arg1:string,arg2:string):Promise<void>;

export function SSHConnect(arg1:sshx.ConnectConfig):Promise<void>;

export function SSHDisconnect():Promise<void>;

export function SSHExec(arg1:main.ExecRequest):Promise<sshx.ExecResult>;

export function SSHGrepRecursive(arg1:main.GrepRecursiveRequest):Promise<sshx.ExecResult>;

export function SSHGuardAnalysis(arg1:string):Promise<sshx.ExecResult>;

export function SSHIsConnected():Promise<boolean>;

export function SSHSearchFlags(arg1:main.FlagSearchRequest):Promise<sshx.ExecResult>;

export function SSHShellResize(arg1:number,arg2:number):Promise<void>;

export function SSHShellWrite(arg1:string):Promise<void>;

export function SSHSignalPids(arg1:main.SignalPidsRequest):Promise<sshx.ExecResult>;

export function SSHStartShell(arg1:main.StartShellRequest):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function StartLocalForward(arg1:main.StartForwardRequest):Promise<sshx.ForwardRule>;

export function StopLocalForward(arg1:string):Promise<void>;
